server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate     /etc/nginx/ssl/patchguard.crt;
    ssl_certificate_key /etc/nginx/ssl/patchguard.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location /api/ansible/ {
        proxy_pass         http://patchguard-api:8000;
        proxy_read_timeout 300s;
        proxy_connect_timeout 10s;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/windows/ {
        proxy_pass         http://patchguard-api:8000;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/patches {
        proxy_pass         http://patchguard-api:8000;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /api/lynis {
        proxy_pass         http://patchguard-api:8000;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass         http://patchguard-api:8000;
        proxy_read_timeout 60s;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
