# ============================================================
# inventaire_windows.ini
# Liste des serveurs Windows geres par Ansible via WinRM
# PatchGuard v2.0
# ============================================================

[serveurs_windows]
win-srv1 ansible_host=192.168.56.201
win-srv2 ansible_host=192.168.56.202

[serveurs_windows:vars]
ansible_user=Administrateur
ansible_password=MotDePasseWindows
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
