# ============================================================
# inventaire.ini
# Liste des machines gérées par Ansible
# TFE - Bachelier en Informatique et Systèmes - 2025
# ============================================================

[serveurs_cibles]
srv-cible1 ansible_host=192.168.56.101
srv-cible2 ansible_host=192.168.56.102
srv-cible3 ansible_host=192.168.56.103


[serveurs_cibles:vars]
ansible_user=raylab
ansible_ssh_private_key_file=/root/.ssh/patch_key
ansible_become=yes
ansible_become_method=sudo
